# Generated by Django 4.1.2 on 2022-10-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10)),
                ('X', models.IntegerField()),
                ('Y', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Export',
            },
        ),
    ]
